<a href="https://colab.research.google.com/github/dKanikao26/ML_Leanings/blob/main/handling_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
order = pd.read_csv('/content/orders.csv')
messages = pd.read_csv('/content/messages.csv')

In [2]:
order.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [3]:
order['date']

0      2019-12-10
1      2018-08-15
2      2018-10-23
3      2019-08-17
4      2019-01-06
          ...
995    2018-10-08
996    2018-12-06
997    2019-05-07
998    2019-03-03
999    2019-10-15
Name: date, Length: 1000, dtype: object

In [4]:
order['date']= pd.to_datetime(order['date'])

In [5]:
order['date']

0     2019-12-10
1     2018-08-15
2     2018-10-23
3     2019-08-17
4     2019-01-06
         ...
995   2018-10-08
996   2018-12-06
997   2019-05-07
998   2019-03-03
999   2019-10-15
Name: date, Length: 1000, dtype: datetime64[ns]

In [6]:
order['yaer']= order['date'].dt.year
order.head()

        date  product_id  city_id  orders  yaer
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019